"""add cost basis and foreign asset tracking to holdings

Revision ID: 00ec9b5d6b38
Revises: 68ca2a214a54
Create Date: 2026-08-02 09:58:42.822025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ec9b5d6b38'
down_revision = '68ca2a214a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_foreign', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('purchase_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('purchase_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_holdings', schema=None) as batch_op:
        batch_op.drop_column('purchase_price')
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('is_foreign')

    # ### end Alembic commands ###
