"""add ticker and quantity for live price refresh

Revision ID: 116cc35107cf
Revises: 00ec9b5d6b38
Create Date: 2026-08-02 10:20:01.135557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116cc35107cf'
down_revision = '00ec9b5d6b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticker', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_holdings', schema=None) as batch_op:
        batch_op.drop_column('quantity')
        batch_op.drop_column('ticker')

    # ### end Alembic commands ###
