"""add target_date to goals for pace tracking

Revision ID: 400998e5fb0c
Revises: d2f8263dc037
Create Date: 2026-07-29 05:11:25.505583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400998e5fb0c'
down_revision = 'd2f8263dc037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('target_date')

    # ### end Alembic commands ###
