"""sip plans support multiple fund allocations

Revision ID: 9038a270ae77
Revises: 02d260bb58d7
Create Date: 2026-08-02 17:02:04.228870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9038a270ae77'
down_revision = '02d260bb58d7'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('sip_fund_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sip_plan_id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['investment_holdings.id'], ),
    sa.ForeignKeyConstraint(['sip_plan_id'], ['sip_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sip_fund_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sip_fund_allocations_sip_plan_id'), ['sip_plan_id'], unique=False)

    # Preserve existing single fund links as allocation rows before the old
    # column goes away — each SIP that already funded one holding keeps doing
    # exactly that, just represented as a (single-row) allocation now.
    op.execute("""
        INSERT INTO sip_fund_allocations (sip_plan_id, holding_id, amount)
        SELECT id, linked_holding_id, amount FROM sip_plans WHERE linked_holding_id IS NOT NULL
    """)

    with op.batch_alter_table('sip_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sip_plans_linked_holding_id'), type_='foreignkey')
        batch_op.drop_column('linked_holding_id')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sip_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_holding_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sip_plans_linked_holding_id'), 'investment_holdings', ['linked_holding_id'], ['id'])

    with op.batch_alter_table('sip_fund_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sip_fund_allocations_sip_plan_id'))

    op.drop_table('sip_fund_allocations')
    # ### end Alembic commands ###
