"""add sip plans and recurring deposits

Revision ID: d2f8263dc037
Revises: 5250595c9ca5
Create Date: 2026-07-29 04:39:01.551616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f8263dc037'
down_revision = '5250595c9ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_deposits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_deposits_user_id'), ['user_id'], unique=False)

    op.create_table('sip_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sip_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sip_plans_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sip_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sip_plans_user_id'))

    op.drop_table('sip_plans')
    with op.batch_alter_table('recurring_deposits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_deposits_user_id'))

    op.drop_table('recurring_deposits')
    # ### end Alembic commands ###
